[package]
name = "os"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
poem-openapi = "5.1.16"
tracing = "0.1.44"
ssh-key = { version = "0.7.0-rc.11", features = ["ed25519", "rsa", "rand_core"] }
tokio-util = "0.7.11"
tokio-stream = { version = "0.1.18", features = ["sync"] }
futures = "0.3.32"
thiserror = "2.0.18"
tempfile = "3.27.0"
ipnet = "2.12"
libc = "0.2"
getrandom = "0.3"
dashmap = "6.2.1"
paste = "1.0"
zeroize = "1.9.0"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite"] }
auto-di = "0.6.0"
base64 = "0.22"
uuid = { version = "1.2.2", features = ["v4", "serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
sh_macros = { path = "../sh_macros" }
async-trait = "0.1"
russh = "0.45"
russh-keys = "0.45"
