pub mod custom;
pub mod discord;
pub mod gotify;
pub mod lark;
pub mod mattermost;
pub mod ntfy;
pub mod parse;
pub mod pushover;
pub mod resend;
pub mod slack;
pub mod teams;
pub mod telegram;
pub mod webhook;

pub use custom::send_custom;
pub use discord::send_discord;
pub use gotify::send_gotify;
pub use lark::send_lark;
pub use mattermost::send_mattermost;
pub use ntfy::send_ntfy;
pub use parse::parse_addresses;
pub use pushover::send_pushover;
pub use resend::{send_resend, send_resend_to};
pub use slack::send_slack;
pub use teams::send_teams;
pub use telegram::send_telegram;
