// @generated by @openoxide/vite; do not edit.
declare module 'virtual:openoxide-live' {
  export type Todo = { id: number; title: string; done: boolean };
  export function useTodos(): {data: Todo[] | undefined; connected: boolean; loading: boolean};
}
