// @generated by @openoxide/vite; do not edit.
declare module 'virtual:openoxide-live' {
  export type Todo = { id: number; title: string; done: boolean };
  export type MetricSample = { sequence: number; value: number };
  export type ActivityEvent = { sequence: number; message: string };
  export function useTodos(): {data: Todo[] | undefined; connected: boolean; loading: boolean};
  export function useMetrics(): {data: MetricSample | undefined; connected: boolean; loading: boolean};
  export function useActivity(): {data: ActivityEvent | undefined; connected: boolean; loading: boolean};
}
