import {execFileSync} from 'node:child_process';
import {existsSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';

const VIRTUAL_ID = 'virtual:rustploy-live';
const RESOLVED_ID = `\0${VIRTUAL_ID}`;

function findManifest(start) {
  let current = start;
  while (current !== dirname(current)) {
    const candidate = resolve(current, 'Cargo.toml');
    if (existsSync(candidate)) return candidate;
    current = dirname(current);
  }
  throw new Error('[rustploy] Cargo.toml not found above Vite root');
}

function loadManifest(root) {
  const cargo = findManifest(root);
  const stdout = execFileSync('cargo', ['run', '--quiet', '--manifest-path', cargo, '--bin', 'rustploy-live-manifest'], {encoding: 'utf8'});
  return JSON.parse(stdout);
}

function runtimeSource(manifest) {
  const endpoints = manifest.endpoints.map((endpoint) => `
export const ${endpoint.hook} = createLiveHook(${JSON.stringify(endpoint)});`).join('');
  return `
import {useEffect, useMemo, useState} from 'react';
import {io} from 'socket.io-client';
const sockets = new Map();
function createLiveHook(metadata) {
  return (...args) => {
    const key = JSON.stringify(args);
    const endpoint = useMemo(() => ({...metadata, args}), [key]);
    const [data, setData] = useState();
    const [connected, setConnected] = useState(false);
    useEffect(() => {
      let socket = sockets.get(endpoint.namespace);
      if (!socket) { socket = io(endpoint.namespace, {path: '/socket.io'}); sockets.set(endpoint.namespace, socket); }
      const subscription = {endpoint: endpoint.endpoint, args};
      const subscribe = () => { setConnected(true); socket.emit('live:subscribe', subscription); };
      const disconnect = () => setConnected(false);
      const update = (message) => {
        if (message.endpoint === endpoint.endpoint && JSON.stringify(message.args) === key) setData(message.data);
      };
      socket.on('connect', subscribe); socket.on('disconnect', disconnect); socket.on('live:update', update);
      if (socket.connected) subscribe();
      return () => { if (socket.connected) socket.emit('live:unsubscribe', subscription); socket.off('connect', subscribe); socket.off('disconnect', disconnect); socket.off('live:update', update); };
    }, [endpoint, key]);
    return {data, connected, loading: data === undefined};
  };
}
${endpoints}
`;
}

function declarationSource(manifest) {
  const types = manifest.types.map((type) => `  export type ${type.name} = ${type.definition};`).join('\n');
  const hooks = manifest.endpoints.map((endpoint) => `  export function ${endpoint.hook}(${endpoint.parameters ?? ''}): {data: ${endpoint.result} | undefined; connected: boolean; loading: boolean};`).join('\n');
  return `// @generated by @rustploy/vite; do not edit.\ndeclare module '${VIRTUAL_ID}' {\n${types}\n${hooks}\n}\n`;
}

export function rustploy() {
  let source;
  return {
    name: 'rustploy-live',
    enforce: 'pre',
    configResolved(config) {
      const manifest = loadManifest(config.root);
      source = runtimeSource(manifest);
      writeFileSync(resolve(config.root, 'src/rustploy-live.generated.d.ts'), declarationSource(manifest));
    },
    resolveId(id) { if (id === VIRTUAL_ID) return RESOLVED_ID; },
    load(id) { if (id === RESOLVED_ID) return source; },
  };
}
